### ISSUE TITLE
trips over variable filename?

### ISSUE THREAD

**Issue by beno** [jeromegn/kilt#10]
This works fine

```
Kilt.render("./templates/template.slang")
```

but when I try to do

```
template = "./templates/template.slang"
Kilt.render(template)
```

everything blows up with

```
1.     String.build do |__kilt_io__|
2.       Kilt.embed(template, "__kilt_io__", )
3.     end
4.   

Kilt.embed(template, "__kilt_io__", )
             ^~~~~~~~

undefined macro method 'Var#split'
```

This seems odd? Is there another way I should pass in variable template names?

**Comment by jeromegn** [comment]
Hey @beno!

That's a limitation of Crystal's macros. Can't pass variables to macros :(

Macro generates code on compile-type and so has no way of knowing the value of that variable at that time.

**Comment by jeromegn** [comment]
Closing for now as it is a limitation of the language.

**Comment by beno** [comment]
Aha, that makes sense. Bit it does rather limit the use cases for Kilt.

**Comment by jeromegn** [comment]
Indeed :(

It's meant as a unified API for rendering templates. Kemal uses it. Gives developers more choice.

**Comment by beno** [comment]
I notice Slang also relies on macros to do it's magic, so same problem there. What would be the way to remedy this? Write templates to a temp file and render that (doesn't sound very performant)? Or is there a macro-less way to render Slang?

**Comment by jeromegn** [comment]
Slang, Crustache, ECR (Crystal's standard lib's template rendering) use macros.

There isn't a way around it I fear.

**Comment by beno** [comment]
How about using a macro to generate the Kilt/Slang call? How does Kernal do it? _heads over to Kernal_
