### ISSUE TITLE
multiline javascript strings using backtick do not compile

### ISSUE THREAD

**Issue by fridgerator** [jeromegn/kilt#14]
For instance, when using Vue inline:

```javascript
new Vue({
  el: '#app',
  template: `
    <div>
      something
    </div>
  `
})
```

It seems like the `run` macro raises the exception: `unterminated parenthesized expression`

**Comment by fridgerator** [comment]
I should specify I was using slang

**Comment by jeromegn** [comment]
@fridgerator that does sound like [slang](/jeromegn/slang) specific issue!
