### ISSUE TITLE
Crystal 1.0.0 compatibility

### ISSUE THREAD

**Issue by petr-fischer** [jeromegn/kilt#26]
Can you set crystal version in the shard.yml file?

Something like:
```
crystal: 1.0.0
ior
crystal: >= 0.34
etc
```
If there is no crystal version in shard.yml, "shards" utility treats it as < 1.0.0 requirement.

**Comment by jeromegn** [comment]
Thanks, just merged a PR that fixes this and bumped the shard version to 0.6.1

**Comment by petr-fischer** [comment]
Can you release also 0.4.1 with this fix (correct crystal version in the shard.yml)? 0.4.1 will fix current Kemal 1.0.0, because there is kilt ~> 0.4.0 dependency in the Kemal.

Maybe this is work rather for Kemal authors (adopting the latest Kilt), I know, I know...

**Comment by jeromegn** [comment]
Just released v0.4.1.

Kemal should probably upgrade! I think newer versions just add support for more template engines.
